"""
Gate 6: Comprehensive Test Suite for Hardening, Observability, Spend Limits & GDPR Account Deletion.
Validates:
1. Structured Correlation IDs: X-Request-ID & X-Response-Time-Ms on all responses
2. Dependency Health Probe: /health/dependencies checks DB, LLM, Hindsight, and Storage
3. Hard Spend Limits Enforcement (Drill): Raises BudgetExceededException (HTTP 402) at ceiling
4. GDPR Account Deletion: Cascades to all tenant entities and pseudonymizes audit logs
5. Google OAuth 2.0 Integration: Generates consent URL, tracks status, and handles disconnect
6. OpenClaw Autonomous Reconnaissance: Extracts company & attendee intelligence with unverified_assumption
"""
import uuid
from decimal import Decimal
import pytest
from httpx import AsyncClient, ASGITransport
from sqlalchemy import text

from apps.api.app.main import app
from apps.api.app.core.db import engine, get_tenant_session
from apps.api.app.core.security import create_access_token
from apps.api.app.services.cost_service import CostService, BudgetExceededException
from apps.api.app.providers.openclaw_adapter import OpenClawAdapter

async def seed_user(user_id: str, budget: float = 25.0, spend: float = 0.0):
    unique_email = f"user_{uuid.uuid4().hex[:10]}@example.com"
    async with engine.begin() as conn:
        await conn.execute(
            text("SELECT public.seed_test_user(CAST(:u_id AS UUID), :email, CAST(:budget AS NUMERIC), CAST(:spend AS NUMERIC));"),
            {"u_id": user_id, "email": unique_email, "budget": budget, "spend": spend}
        )

# ==============================================================================
# 1. Observability & Health Probes
# ==============================================================================

@pytest.mark.asyncio
async def test_correlation_id_and_observability_middleware():
    """
    Validates that every HTTP response carries a correlation ID and latency header.
    """
    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as client:
        # Request without incoming ID -> autogenerated
        resp = await client.get("/health/live")
        assert resp.status_code == 200
        assert "x-request-id" in resp.headers
        assert "x-response-time-ms" in resp.headers

        # Request with client supplied ID -> echoed back
        custom_id = f"client-req-{uuid.uuid4().hex[:8]}"
        resp_custom = await client.get("/health/live", headers={"X-Request-ID": custom_id})
        assert resp_custom.headers["x-request-id"] == custom_id


@pytest.mark.asyncio
async def test_dependency_health_probe():
    """
    Validates /health/dependencies probes PostgreSQL pool, Groq config, and Hindsight.
    """
    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as client:
        resp = await client.get("/health/dependencies")
        assert resp.status_code == 200
        data = resp.json()
        assert data["status"] in ("healthy", "degraded")
        deps = data["dependencies"]
        assert "database" in deps
        assert deps["database"]["status"] == "connected"
        assert "latency_ms" in deps["database"]
        assert "llm_provider" in deps
        assert deps["llm_provider"]["status"] == "configured"
        assert "memory_service" in deps
        assert deps["memory_service"]["provider"] == "hindsight"
        assert "object_storage" in deps


# ==============================================================================
# 2. Hard Spend Limit & Budget Rejection Drill
# ==============================================================================

@pytest.mark.asyncio
async def test_hard_spend_limit_enforcement_drill():
    """
    Drill: Proves that when user spend reaches the monthly budget ($25.00),
    CostService strictly blocks any further LLM reservations with BudgetExceededException.
    """
    user_id = str(uuid.uuid4())
    # User has spent $25.00 of their $25.00 monthly budget
    await seed_user(user_id, budget=25.0, spend=25.0)

    # Attempting to reserve even $0.001 must raise BudgetExceededException immediately
    with pytest.raises(BudgetExceededException):
        await CostService.reserve_budget(
            user_id=user_id,
            estimated_cost=Decimal("0.0050"),
            operation_type="outcome_proposal"
        )

    # Verify status reports hard_stop
    status_info = await CostService.get_budget_status(user_id)
    assert status_info["status"] == "hard_stop"
    assert status_info["percentage_used"] >= 100.0


# ==============================================================================
# 3. GDPR Account Deletion Lifecycle
# ==============================================================================

@pytest.mark.asyncio
async def test_gdpr_account_deletion_workflow():
    """
    Validates full GDPR account deletion:
    1. DELETE /api/v1/users/me
    2. Cascades to tenant relational entities (meetings, contacts, preferences)
    3. Anonymizes audit events (user_id = NULL with pseudonymized SHA-256 hash)
    4. Purges user profile completely
    """
    user_id = str(uuid.uuid4())
    await seed_user(user_id)

    # Populate child records for this tenant
    async with get_tenant_session(user_id) as session:
        # Create meeting
        m_res = await session.execute(
            text("""
            INSERT INTO public.meetings (user_id, title, start_time, end_time)
            VALUES (:u_id, 'GDPR Test Meeting', NOW(), NOW() + INTERVAL '1 hour')
            RETURNING id;
            """),
            {"u_id": user_id}
        )
        meeting_id = m_res.scalar()

        # Create audit event
        await session.execute(
            text("""
            INSERT INTO public.audit_events (
                user_id, original_user_hash, event_type, resource_type, resource_id
            )
            VALUES (
                :u_id, 'pending_hash', 'user_login', 'user_profile', :u_id
            );
            """),
            {"u_id": user_id}
        )

    token = create_access_token({"sub": user_id, "role": "authenticated"})
    headers = {"Authorization": f"Bearer {token}"}

    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as client:
        # Execute GDPR Account Deletion
        del_resp = await client.delete("/api/v1/users/me", headers=headers)
        assert del_resp.status_code == 204

    # Verify PostgreSQL database state
    async with engine.connect() as conn:
        # 1. Profile must be completely deleted
        prof = (await conn.execute(
            text("SELECT id FROM public.user_profiles WHERE id = :u_id;"),
            {"u_id": user_id}
        )).scalar()
        assert prof is None

        # 2. Cascaded child records must be gone
        meet = (await conn.execute(
            text("SELECT id FROM public.meetings WHERE user_id = :u_id;"),
            {"u_id": user_id}
        )).scalar()
        assert meet is None

        # 3. Audit events survive with user_id NULL and anonymized hash
        audit_row = (await conn.execute(
            text("SELECT user_id, original_user_hash FROM public.audit_events WHERE resource_id = :u_id;"),
            {"u_id": user_id}
        )).mappings().first()
        assert audit_row is not None
        assert audit_row["user_id"] is None
        assert audit_row["original_user_hash"] != "pending_hash"
        assert len(audit_row["original_user_hash"]) == 64  # SHA-256


# ==============================================================================
# 4. Google OAuth 2.0 Integration Endpoints
# ==============================================================================

@pytest.mark.asyncio
async def test_google_oauth_integration_lifecycle():
    """
    Validates Google OAuth authorization URL generation, status inspection, and disconnect.
    """
    user_id = str(uuid.uuid4())
    await seed_user(user_id)
    token = create_access_token({"sub": user_id, "role": "authenticated"})
    headers = {"Authorization": f"Bearer {token}"}

    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as client:
        # 1. Get Google OAuth consent URL
        auth_url_resp = await client.get(
            "/api/v1/integrations/google/auth-url",
            params={"redirect_uri": "http://localhost:3000/auth/callback/google"},
            headers=headers
        )
        assert auth_url_resp.status_code == 200
        auth_data = auth_url_resp.json()
        assert "accounts.google.com" in auth_data["authorization_url"]
        assert "calendar.readonly" in auth_data["authorization_url"]
        assert "documents.readonly" in auth_data["authorization_url"]

        # 2. Check integration status (disconnected initially)
        status_resp = await client.get("/api/v1/integrations/google/status", headers=headers)
        assert status_resp.status_code == 200
        assert status_resp.json()["status"] == "disconnected"

        # 3. Disconnect endpoint
        disc_resp = await client.post("/api/v1/integrations/google/disconnect", headers=headers)
        assert disc_resp.status_code == 200
        assert disc_resp.json()["status"] == "disconnected"


# ==============================================================================
# 5. OpenClaw Autonomous Reconnaissance Intelligence
# ==============================================================================

@pytest.mark.asyncio
async def test_openclaw_meeting_reconnaissance_adapter():
    """
    Validates OpenClaw adapter autonomous extraction of company background and attendee intelligence.
    Enforces strict security boundary: intelligence is tagged as unverified_assumption.
    """
    adapter = OpenClawAdapter(enabled=False) # Tests deterministic containment
    recon = await adapter.extract_meeting_recon(
        meeting_title="Enterprise Cloud Security Review",
        attendee_names=["David Miller"],
        company_domains=["cloudflare.com"]
    )
    assert recon["source"] == "openclaw_recon"
    assert recon["epistemic_class"] == "unverified_assumption"
    assert recon["verified"] is False
    assert "company_intelligence" in recon
    assert recon["company_intelligence"]["domain"] == "cloudflare.com"
    assert len(recon["attendee_recon"]) == 1
    assert recon["attendee_recon"][0]["name"] == "David Miller"
